package adhoc;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.stream.Collectors;

public class Delete {

	public static int c = 1;

	public static void main(String[] args) {

		String s = "aceceaacececaecaeaabaacbaceddccbdbddcdbededcabcbaaddbdadcaaccaccededeadebbaeeebdaccebbceddddedeaaaaabcdbebecdaaabdbdcebbbbabaeccadbcaceeadabcccbcbeabdadaedabaaeeeddebeaddecabedceaaebceaaccbcdedcaacedceaaddaebaceaeaedeeaaccdebdcccbaedebebacdbaedabeceadaeeeddbdaacebaabeebcbaaaeeccedcaabbeddcadbddcddbadccaeecbdddebdabecadcdaccdcbcbbbabcbdddadeabbcbccebbbebbabbbbeebebadabcbaeadabadbbababdcbadbbaabeabecdeabeddabbbdbcdccddadacabedaeccaabaebceaceabececcdbbacdabdbbaeaeeccbcceaababbeccaeebcedcceabceaddcedeebcebbebcdcaaddccbaacebabdabcceecbbcdeebacaaaecbdaaddaadabddacecdcddcceecddcededadacabdeadebbbcdccacabcebdebbbeacaacbeebcddabeaedaddcbadcbcbcadebebcacaeebbadbdcdceedbaabecabbeedebdabcbacabeadddcababebedabcacacadcaeeacbabecbdadecacabdebebbdeeeccecececabdeceeacdbddcdddebaeeddcaddecbebabdeedacddecccbccdbedecacbbebccccebbadcaeaeccedcaaeeaddabedcebedbcaeeaabacbbcadcadeeeaacbececcbdeeceecaaddcebbbeacacddedaabdeabddeccacebdccbdedbddccadbdddaabdebbbacaacabeacedcdedbeeadbdcacbbbebabecabacdceeedabaeabdbbdeeaadcdadcdaccccbabcbbdaaebcbdbcdccdcebbbebbddbaaeeabebebaeaaddaabccaeeeeeedebbccaccdedcebdaadddcccaceaeacecbeecddeeaeceedcdcacddabeaadcccabaebacebebceecebbdededaacbcbdeacabcedccecbdcedcdaecedbadaaecbbdeebccecddbcbaaabbddccbdacddcadebadacdccaeabddacdceabbdcccabaaaabeaecddbaeceacdadacdeebcedccbbdaadbcbbeadbacaedeebaebdacabcdbacabebbadacdadecabbeebceaddbbbdbbddbcdbcdebaecccdbcbacceddebceceecabcdbaacecbbdbccbabeabaabdaebebbaaeabedaaedbbaeeaacebbcddcadccbdbbeedadadedeeaaedcdeeccecedbbaeddbecaaadeeaeadcaacecceedcabddcacbebebbbaeaccadeedcaddbeedcdbdbabdabccbdaeebbadbaaccedbabcedcbebceadaebdaeecabccaecddbcadaaebeadacddcadcabcbdecaeccbddedbccbdabbcbccaeaeabcbdeecabcbbeaddecdaeccbceceeebccdccdaeaabcceaeaacdcacadacdceaeceeeeaceabbecbbcaceddacebdcbebeabcdbddceeabacbecbecbebdecbabeeadacbdadbbebaaebacecbadbbdbabebecdbecdebbebcaccdddccebbbcbcecbcaeaeedaaddcaedcacebdcdaabdebadcbdaaeeedaaacdeabbdbeedcebaaecadeeadbeabecdeeaadcccaaeedaecddedbeabcacadceecbdacabdbdeebacadeaeccbbaabebdeadabecbdabeaacbebcedebbacaebcaeeccdbceeaedbceacaadbaddeabcdadedaceecbebcdbcbdacdccbaeaecbbeddcaccbebddecceaaacaeeeabbccbebcdeceedaddaceecccaaeaecdedcacbcdeaecaaeedacaebadaebacaccdddebeddacbdeeeaeccacbeacebacccaeedaacaecccabaadcdceeadbcccdbeecabacdaabcbabeeacddeddbcbbdeadaabbccddeacecbebeeeebdadaaddecddbcbcbadeedadcdadbbdedcadbbabbcecdbcebcabbbedbadcdecdedeedbcbbeaabecaadacebebcbeccaeacbbbecabeaebabaeaeacdeabebcbdbdacdbbedacedacdbaeaebeccbdcececbddacaedebeabcebdbaecccdcecddbecbadbacbabcecddadecabbbdcccaeeadcceaebacdbcaddbbbcbbbcacbbcbdddcdcdbdddccabbabdedadcddcbddbbebacddceeaaebdecebbaacdbcedbaaccbcdacdeccaccacadbabdadaceccbcdaccacdccdbcbaabcaddbbdcbcadaeededabdebeadbaabdebcbedacaecdbdcaddddeeaecdaeeadacbecbceccebedbabbbdddcbdcbbadccbabadabecaaeeaddcaaaeebecdbbdcbbbeacdaadacbababdecccedddbebebaaadaccbcbdacbbaabdeddaeacddcebddcecdecbcaabddaccecacbbacbbeabeebcdbeadebeaedebbcabcceedbccbaeeebccabddaedbecabbbedbccadeadaeeecacbecdbdccaabadbdcacabadacdcaeaabbccccedebdceecbdaedaebecccaeaaecadbdbaebcbcdeddabbcebbaccadceaecadabeebeccecbebccacadcacbcebbaaccbecdabcaeeecdeccddedbbabccaceaceacbbbedddeadebddedbbaacababdcadbcceaadeceecaeebaabddeecdbcaccecabbaecdaeebaededdcdaadadaeebebaaecddeeebceedbaddcdacebacbbececedabbeeebaeeccbcbedbbcdedcdbdbccaddaddbeeadbcbcecadaedadaedabcbdaaabadccabdbdeddaaccecabaaeaaeeeacceecdabbdaaceaadbeccbbbeabbaeededaccadabdaabebbbabdbabeedbcbaabeeebadbbeceeaecccdceccaadcdabedebbedbbbbaedbcdabababbbddccbaaeddbaababedeaeecbdcacdebebaceeecdbdaadcceacbdcddadcaaaabaaebceeeaccddecccecebaaeddbecbeedebbbbcbaddaebcdeaebbaeaaaeabcabaacdaeaacdedcbeaeadbadeeebddbcdecccdedcdbaaedeeabadebdaacebbdadcabebcddacbabdebdadcbdbccccbccbbdacebdedbabddadbbaebcbedcbedcacdecccdadeadadecdbcceddececeaeabbbbbbdabaeadaceabbebeddbacbadceeccbaabdeaeaebddebdcbeeddeaebdabdadddaecaaacbdabdedadaecabceaeaebcdbebdcbdcedcebddeacbbabeaaabdeccddcbeddccddccaeddbbcbadbceadcbcdebddcbcededdbebbbacdbaaaabeeebbbecbabbdaedbedacbabaebbbdddaadedcccbebacecdadcceabddbbacaecedceadbaeacaeedaebcdaceeeddbbadadacbcddbbcdebeacabdaccaaccccecceaccbeaedaebbebabecaaabcacadccebaadceeddbaadeacacacbaeeecccebeaeeeccabbeebbaeccdbaacdcdeeeacadcdedacecbcdbdebceebcddeedecccbbbedcdadcaebabbbcbaaeabdbdbdabaeedeccebdbbdceccaddaccceabecdaebbbddcccdcadaacaaeecbbdbabececdacedaebcabdeebbbebebbcadcabcdebaaeabecdbbabddecaddddbbcaaacaeaadecdbeaaaeedceaacaadeeebcdacbcecaceccadaaceabeabeeeaacbcbcdceeacadeebbbdccceaabaabababcbebaacbbdccbccbdccadaaeeabecbbeebdecdddcecacdcdadbeeeaaeeaeeaacbbdcdaaddbaeaacabdaedcacedcacdcbebedaebcbdcaceabdacacbbdebabcbdebeadecaaebceabecbdeeddaababdebaddadcaaeeecbeaeaaaadedebdbbabcdacbbecebdaaccbbbdcaeecdccaddebdbbcbebcdbeccdaceecdedaaebdaebbcccdaddebbcbaebaeacacceddedcdccacacaaaeabccbcdebecbdacdbeacadcacaeecccdbbeccadceaddabdaabaabddabceadddcacbacdebceebdceedaeddebdbceebeaaeceecaeabddddbccbcadbdbcdabdcadbacccabbddaacadebddedddaecbbeeecebddacaaaceaddcaddadeccddbaedaacadeabaddbaabddbedecbeeeeceedadabdeebdddaebcdedbeccabcbbedacdaaeabcacaabdbaeeeaebeddddbababaeeeadbbaddaebccbdeeedbbacedcbcbabcdabdebcedddcedddedcabadbaedbbbdbcbabeeebecebcecedeaccadcabaaaedeceeecacebaaadccbcecbedebdbdcebaecebbedceaeaeccbedccecceadccbbbacbddbcecbbcebcaadddcaceedbadcbdacedaddcbeabbaaceddaeaabceccbbacacdddeeeadcbdcdbcdaeceaedbcecdcaecdaccaabdaacbadbacccacdbacbbcadabbeabcdceabaacaceadccbcaeadaabaebdcdcbacdcaadeccabdeebcecaedbddeacbcdbbbdbbedccbdacbacddabeeabbdeccdeaedbeeebadbdddbebeecbcbdcceeebabacccbbbbcecadacabdcacbadccaaaaadabeeeecdccdaeededbdeadebecebbcabcdaddbbbcccabadbbabdeabecaaaadaeebacacbebecbeeaacbdbceecaaeabadbcdcdbcdeacacebdedecadaecaaacbebccacaeaaebbbecbabcccaddbcdaeedddabaeaedbbdecdcaeeddccbacbccbdbabdabacddabcadbbceeebeaccbaacacbabcdaaccbcccdbcecbacecbccdbcbcbcdebbecaebcdcbcbccdadadceebcdeebdcdcbcdabccccadcabbcbadaedaaeadbeebaaccaadbcbceedbdedbbcacaeeecaceadecececeaedebbdacdbbeebdbcdbbbabdccaaecbdaebbcaeaadbddebeaccbceabdbaccbabedcdbbedadbaccbbaccecdcabcccbaacbceabbeebaeaadbdabebcbddcbaedadeedeabebaaabcacbddccabebbccaabecccbdbededecebdbdeedeccceddcceeeeccecdadeeedabcceddccbbdddcdacacaddddaeaeaccacbecaeddeddcdbbdddecddedadcacdccbaeedbbedeaebdbdaeebcddaccbbedeceeccbeecadcbccdbcabadacdedbaceaeeaebadcbbbbeeddedbebbeadceedccabddcddceebbaddeadeeeedabeaaadbcceebaeeddedceeadabcbbacdcedbdbcbeeeaedbacdeaddbadbdceedeecddeeaebbdedeeebaececcedcabdadecbbcaccebeeccaeaebadaecaaeadadaeaacadebabeecdeedaaeabbdadeacdcaedebbdcccceadaecccbabbaadebcdcbceddecdddaaeadabbeebdbdaaaaedecbcedeaceabcbccbdadeedaebaabcaddeececabceddbcadbdddcdbbbeeaedcadaabbcedaaccdbbaacedbbcacbdddbdbaebdbcbaebaebabecbebaedabebdecdddccdeeedebecaaeceaeacdbbbdceaeaacebaccecacdeaadbdaaddebeadbacdcaabcaddedcccceeccdacbdadaedcdebadeddaadbedaacdadddebbeeddcdcaccecbcbabbbdeeecacedceacbaaacdbdeececccdbdceeeadbabdccaabdbacebeabdbddcadbbacacdebcceccecbdcbabbccbbcbeabdcbaceabaceaeeadaeccdaedeaabaeddbaadcbabccaccdabdcdbecccbbbdaccdcacaadccdbeaeceedabdbaeaebcdacebcadeaecdcbbcbedabdaadebeecebabccebdaaebacdabadaedadcbdebdadacadaeadbabeeceadeeeabaaddacaeebdebcbddeaecabedbedaceccbeacccdeedbeacccabdbdaecdbddeedbdbcbacaaacdcdbaccacecacdedddeeadcbbabccabdbbeabacccdceaaabebabbecdaecdbbbddcebbedcebbdaeaeabadaeddeeeedddaaccccabaaaebcbcddacaaaadebdcecbccaaaaebaebdbdbaadcacadcbeecbdaccbdddbdbcaccacdeacbcbcabcdbdebaaaeaeaabeecbbebcdeebebaeeeabeebdbdcbcaeceaadcdbadeadceaedbeecedbcacbbecddcebacdedcbddcaccaabaedabeceaccddbddadcedceddbcbedcabaddbebadeadbcbedcbaacebdceacadeeeadbeeceeaaebceecaccccedcbbadbbadedeaaebceaedaacbccdabdbcabbebeaddeeecababddabdeacecaddabeaecaededcecdbaeadccbceecbddbbdbbecbbbbdcbedcaeeadceeebcedcbedbdccbebedbaebbcebdbacccababbaaadeccbaeddbebbdecdbbcadeaeeaeabcccbdaceedadadcadcaccddebecbedecdabcbcdebbdcdcebbaebddedbdeccaeacbeeebaeaeeebbadcddebacbabdeadccdbccedddcaccceecbeadaeccccedcdadabdcdaeceeeccebaeebecdddeeaaabdcbceebccaccbacdeabbedbccedcaedebedbcacdedbcedcedaeeaeeaeebbebbedbcedcaebbeaeeecebebaecbdeabedbdabccdd";
		int ans=new Delete().numSplits(s);
		
		System.out.println(ans);
		
		byte b1=3;
		byte b2=4;
		
		byte b3=(byte)(b1+b2);
		
		System.out.println("abc"+10+20);
		System.out.println(10+20+"abc");
		
	}

	public int numSplits(String s) {

		int k = 0;
		for (int i = 1; i < s.length(); i++) {

			String s1 = s.substring(0, i);
			String s2 = s.substring(i, s.length());

			boolean b = aux(s1, s2);

			// System.out.println(s1+":"+s2+":"+b);
			if (b) {
				k = k + 1;
			}
		}

		return k;
	}

	public boolean aux(String s1, String s2) {

		Set<Character> set = new HashSet<>();

		for (Character ch : s1.toCharArray()) {
			set.add(ch);
		}
		int i = set.size();

		set.clear();

		for (Character ch : s2.toCharArray()) {
			set.add(ch);
		}

		if (i == set.size()) {
			return true;
		}

		return false;

	}

	public static int m(int[] nums) {

		if (nums.length == 1)
			return 0;
		int left = 0;
		int right = nums.length - 1;
		while (left <= right) {
			int mid = left + (right - left) / 2;

			if (mid > 0 && nums[mid - 1] > nums[mid]) {
				right = mid - 1;
			} else if (mid == nums.length - 1)
				return mid;

			else if (nums[mid] > nums[mid + 1]) {
				return mid;
			} else if (nums[mid + 1] > nums[mid]) {
				left = mid + 1;
			} else {
				right = mid;
			}
		}
		return -1;
	}

}
